---
title: HW1
author: Megan Tebbenhoff
output: github_document
---

This is my solution for HW1.

```{r}
library(tidyverse)
```


## Problem 1

##### Creating a data frame with the specified elements.
```{r_create_df}
prob1_df = 
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "low","low", "mod","mod","mod","mod","high","high","high"))
)
```

##### Taking the mean of each variable in my data frame.
```{r_mean_pull_var}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_gt_0))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df, factor_vec))
```

I can take the mean of numbers and logical variable but not character or factor variable.

##### Converting the variables in my data frame to numeric variables.
```{r_as.numeric}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))
```

I cannot convert the character variable to numeric, but I can convert the logical and factor variables as numeric. Since the logical variable is on a binary scale, it makes sense that we could calculate the mean of this set of responses, even though it would not have any meaning.

##### Calculations using converted variables.
```{r_var_conversion_calculations}
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
as.factor(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
as.numeric(as.factor(pull(prob1_df, samp_gt_0))) * pull(prob1_df, samp)
```

## Problem 2

Before beginning Problem 2, I installed "palmerpenguins" to obtain the penguins dataset.

##### Creating the data frame and getting summary information.
```{r_data_summary}
data("penguins", package = "palmerpenguins")
penguins_df = 
  (summary.data.frame(penguins))
penguins_df
#There are three species with varying numbers of observations: Adelie (152), Chinstrap (68), and Gentoo (124). There are three islands with varying numbers of observations: Biscoe (168), Dream (124), and Torgersen (52). The data was collected between 2007 and 2009, and they collected information regarding sex, body mass (g), bill length (mm), bill depth (mm), flipper length (mm).
nrow(penguins)
#There are 344 rows in this dataset.
ncol(penguins)
#There are 8 columns in this dataset.
mean(penguins$flipper_length_mm, na.rm = TRUE)
#The mean flipper length is 200.9 mm.
```

##### Creating the scatterplot comparing flipper length (mm) and bill length (mm).
```{r_scatterplot}
penguins_plot = 
  (ggplot(data = penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species))
  +geom_point())
penguins_plot
ggsave("penguins_plot.pdf", height = 4, width = 6)
```

